export const ErrorCodes = {
  INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  VALIDATION_ERROR: 'SYS_VALIDATION_ERROR',
  DATABASE_ERROR: 'SYS_DATABASE_ERROR',
  NOT_FOUND: 'SYS_NOT_FOUND',
  UNAUTHORIZED: 'SYS_UNAUTHORIZED',
  FORBIDDEN: 'SYS_FORBIDDEN',
  BUSINESS_ERROR: 'SYS_BUSINESS_ERROR',
  RATE_LIMIT_EXCEEDED: 'SYS_RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
