name: Reusable Flutter Setup

on:
  workflow_call:
    inputs:
      channel:
        type: string
        required: false
        default: 'stable'
      working-directory:
        type: string
        required: false
        default: 'naseeji_factory_supplier'

jobs:
  setup:
    name: Setup Flutter & Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Flutter Setup Action
        uses: ./.github/actions/flutter_setup
        with:
          flutter-version: ${{ inputs.channel }}
          working-directory: ${{ inputs.working-directory }}
